### ISSUE TITLE
how to troubleshoot?

### ISSUE THREAD

**Issue by marade** [m27315/nightingale-docker#1]
Hi. Thanks for making this! It gives me hope I can keep using Nightingale. I've been trying to get your Docker implementation to work, but when I run 'music' all I get is this:

non-network local connections being added to access control list

And that's it. 'docker build' appeared to work fine. Ideas? Is there a way to get more debugging information at least?

**Comment by m27315** [comment]
Sorry, I moved from Gentoo to an Ubuntu 20.04 installation a few months back.  It introduced some incompatibility that I could not unravel, so I started using Rhythmbox.  After banging my head against multiple brick walls, I figured that I was working harder at avoiding work than just biting the bullet and converting to a modern platform.  I listened to all of my music again, reassigning stars to each of them.  It took me a couple of weeks, but it worked.  Rhythmbox also allows me to sync my music automatically to an SD card that I used on my phone, which was my other use case.  FWIW, I've been pleased with the finished solution.
